services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "<FTName | snakecase>"
    ports:
      - "<ports>"
    image: <FTName | snakecase>
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/<FTName | snakecase>
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: postgres_bd
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: <FTName | snakecase>
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
